version: '3'
services:
  tbdev:
    build:
      context: .
      dockerfile: yse.Dockerfile
    container_name: tbdev
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: tbdev
      SERVICE_TAGS: dev
    depends_on:
      - db
    volumes:
      - ./var/www/include/config.local.php:/var/www/html/include/config.local.php
      - ./var/www/include/secrets.local.php:/var/www/html/include/secrets.local.php
      - ./etc/php/conf.d/local.ini:/usr/local/etc/php/conf.d/local.ini
      - appdata2:/var/www/html
    networks:
      - app-network
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - tbdev
    volumes:
      - appdata2:/var/www
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
  db:
    image: mysql:5.6
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: tbdev
      MYSQL_ROOT_PASSWORD: tbdev
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=tbdev
    depends_on:
      - db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  appdata2:
  dbdata:
    driver: local